name = "tusinasaa-worker"
main = "worker/src/index.js"
compatibility_date = "2025-09-28"
[observability]
enabled = true

[[kv_namespaces]]
binding = "LOCATIONS"
id = "033276b4df18419a8eb60a7d42a4efef"
