name = "tusinasaa-worker"
main = "worker/src/index.js"
compatibility_date = "2025-09-28"
[observability]
enabled = true

[[kv_namespaces]]
binding = "LOCATIONS"
id = "MYOxtwHHXntQo5DU94jQx4NSyNjVgVHX"
